#VOLUMIO TRIGGERHAPPY CONFIGURATION FILE
#VOLUME
KEY_VOLUMEUP	1	/usr/local/bin/number_loop.sh "volume&volume=plus" "press"
KEY_VOLUMEUP	2	/usr/local/bin/number_loop.sh "volume&volume=plus" "keep"
KEY_UP		1	/usr/local/bin/number_loop.sh "volume&volume=plus" "press"
KEY_UP		2	/usr/local/bin/number_loop.sh "volume&volume=plus" "keep"
KEY_VOLUMEDOWN	1	/usr/local/bin/number_loop.sh "volume&volume=minus" "press"
KEY_VOLUMEDOWN	2	/usr/local/bin/number_loop.sh "volume&volume=minus" "keep"
KEY_DOWN	1	/usr/local/bin/number_loop.sh "volume&volume=minus" "press"
KEY_DOWN	2	/usr/local/bin/number_loop.sh "volume&volume=minus" "keep"
KEY_MUTE	1	/usr/local/bin/number_loop.sh "volume&volume=toggle" "press"
#
#PLAY PAUSE TOGGLE
KEY_STOP	1	/usr/local/bin/number_loop.sh "stop" "press"
KEY_PLAYPAUSE	1	/usr/local/bin/number_loop.sh "toggle" "press"
KEY_OK		1	/usr/local/bin/number_loop.sh "toggle" "press"
#NEXT PREVIOUS
KEY_NEXTSONG	1	/usr/local/bin/number_loop.sh "next" "press"
KEY_RIGHT	1	/usr/local/bin/number_loop.sh "next" "press"
KEY_PREVIOUSSONG 1	/usr/local/bin/number_loop.sh "prev" "press"
KEY_LEFT	1	/usr/local/bin/number_loop.sh "prev" "press"
KEY_BACK	1	/usr/local/bin/number_loop.sh "repeat&value=true" "press"
KEY_EPG		1	/usr/local/bin/number_loop.sh "repeat&value=false" "press"
KEY_HOME	1	/usr/local/bin/number_loop.sh "playplaylist&name=Radio_0" "press"
#
KEY_NUMERIC_0	0	/usr/local/bin/number_loop.sh "0" "release"
KEY_NUMERIC_0	1	/usr/local/bin/number_loop.sh "0" "press"
KEY_NUMERIC_0	2	/usr/local/bin/number_loop.sh "0" "keep"
KEY_NUMERIC_1	0	/usr/local/bin/number_loop.sh "1" "release"
KEY_NUMERIC_1	1	/usr/local/bin/number_loop.sh "1" "press"
KEY_NUMERIC_1	2	/usr/local/bin/number_loop.sh "1" "keep"
KEY_NUMERIC_2	0	/usr/local/bin/number_loop.sh "2" "release"
KEY_NUMERIC_2	1	/usr/local/bin/number_loop.sh "2" "press"
KEY_NUMERIC_2	2	/usr/local/bin/number_loop.sh "2" "keep"
KEY_NUMERIC_3	0	/usr/local/bin/number_loop.sh "3" "release"
KEY_NUMERIC_3	1	/usr/local/bin/number_loop.sh "3" "press"
KEY_NUMERIC_3	2	/usr/local/bin/number_loop.sh "3" "keep"
KEY_NUMERIC_4	0	/usr/local/bin/number_loop.sh "4" "release"
KEY_NUMERIC_4	1	/usr/local/bin/number_loop.sh "4" "press"
KEY_NUMERIC_4	2	/usr/local/bin/number_loop.sh "4" "keep"
KEY_NUMERIC_5	0	/usr/local/bin/number_loop.sh "5" "release"
KEY_NUMERIC_5	1	/usr/local/bin/number_loop.sh "5" "press"
KEY_NUMERIC_5	2	/usr/local/bin/number_loop.sh "5" "keep"
KEY_NUMERIC_6	0	/usr/local/bin/number_loop.sh "6" "release"
KEY_NUMERIC_6	1	/usr/local/bin/number_loop.sh "6" "press"
KEY_NUMERIC_6	2	/usr/local/bin/number_loop.sh "6" "keep"
KEY_NUMERIC_7	0	/usr/local/bin/number_loop.sh "7" "release"
KEY_NUMERIC_7	1	/usr/local/bin/number_loop.sh "7" "press"
KEY_NUMERIC_7	2	/usr/local/bin/number_loop.sh "7" "keep"
KEY_NUMERIC_8	0	/usr/local/bin/number_loop.sh "8" "release"
KEY_NUMERIC_8	1	/usr/local/bin/number_loop.sh "8" "press"
KEY_NUMERIC_8	2	/usr/local/bin/number_loop.sh "8" "keep"
KEY_NUMERIC_9	0	/usr/local/bin/number_loop.sh "9" "release"
KEY_NUMERIC_9	1	/usr/local/bin/number_loop.sh "9" "press"
KEY_NUMERIC_9	2	/usr/local/bin/number_loop.sh "9" "keep"
