#!/bin/sh
THD_SOCKET=/tmp/triggerhappy.socket
[ -S "$THD_SOCKET" ] || exit

case "$ACTION" in
	add)
		DEVICE="/dev/$DEVNAME"
		[ -c "$DEVICE" ] || exit
		# offer device to triggerhappy daemon
		/usr/sbin/th-cmd --socket "$THD_SOCKET" --add "$DEVICE"
	;;
        remove)
		# nothing to do
	;;
esac
                                                                                                                                                                                                                       ./triggerhappy/files/triggerhappy.init                                                              0000644 0001750 0001750 00000000353 15114636766 017756  0                                                                                                    ustar   pietje                          pietje                                                                                                                                                                                                                 #!/bin/sh /etc/rc.common
START=93

start() {
	/usr/sbin/thd --socket /tmp/triggerhappy.socket --triggers /etc/triggerhappy/triggers.d/ --daemon /dev/input/event*
}

stop() {
	/usr/sbin/th-cmd --socket /tmp/triggerhappy.socket --quit
}
