#VOLUMIO TRIGGERHAPPY CONFIGURATION FILE

#MUTE TOGGLE
KEY_MUTE 0 /usr/local/bin/volumio volume toggle

#VOLUME UP
KEY_VOLUMEUP   1   /usr/local/bin/volume-loop up start
KEY_VOLUMEUP   0   /usr/local/bin/volume-loop up stop

#VOLUME DOWN
KEY_VOLUMEDOWN 1   /usr/local/bin/volume-loop down start
KEY_VOLUMEDOWN 0   /usr/local/bin/volume-loop down stop

#PLAY PAUSE TOGGLE
KEY_PLAYPAUSE 1 /usr/local/bin/volumio toggle

#NEXT
KEY_NEXTSONG 1 /usr/local/bin/volumio next

#PREVIOUS
KEY_PREVIOUSSONG 1 /usr/local/bin/volumio previous

BTN_TRIGGER_HAPPY1 1 /usr/local/bin/power-delay.sh start
BTN_TRIGGER_HAPPY1 0 /usr/local/bin/power-delay.sh stop

KEY_0 0 curl localhost:3000/api/v1/commands/?cmd="playplaylist&name=IR_0"
KEY_1 0 curl localhost:3000/api/v1/commands/?cmd="play&N=0"
KEY_2 0 curl localhost:3000/api/v1/commands/?cmd="play&N=1"
KEY_3 0 curl localhost:3000/api/v1/commands/?cmd="play&N=2"
KEY_4 0 curl localhost:3000/api/v1/commands/?cmd="play&N=3"
KEY_5 0 curl localhost:3000/api/v1/commands/?cmd="play&N=4"
KEY_6 0 curl localhost:3000/api/v1/commands/?cmd="play&N=5"
KEY_7 0 curl localhost:3000/api/v1/commands/?cmd="play&N=6"
KEY_8 0 curl localhost:3000/api/v1/commands/?cmd="play&N=7"
KEY_9 0 curl localhost:3000/api/v1/commands/?cmd="play&N=8"
